### PR TITLE
Update logo.svg

### PR DESCRIPTION
**Pull request by amy-byrum**
Updated to new sans-underscore version of logo

### CODE REVIEW

**Comment by clrcrl** [comment]
The favicon is off in this repo — it's got a white fill and is bigger than other sites. Do we want to update that too?

Normal chrome:
Screen Shot 2020-06-15 at 1 14 31 PM

My chrome with a teal header, where it's more obvious
Screen Shot 2020-06-15 at 1 14 45 PM

**Comment by amy-byrum** [comment]
> The favicon is off in this repo — it's got a white fill and is bigger than other sites. Do we want to update that too?
> 
> Normal chrome:
> Screen Shot 2020-06-15 at 1 14 31 PM
> 
> My chrome with a teal header, where it's more obvious
> Screen Shot 2020-06-15 at 1 14 45 PM

Ah yes, I didn't update the favicon. I can do that too, may need to go through and do that to all of them, I'll check them to be safe.

**Comment by amy-byrum** [comment]
Okay, should be good to go w/ the updated favicon now.

**Review by clrcrl — APPROVED** [review]
So the deploy preview is not showing the updated favicon, but I can see it in this PR — I suspect it's a caching thing, so let's merge it and see how we go!

**Pull request merged**
